
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  schedule: 
    - cron: "0 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 62

    strategy:
      matrix:
        node-version: [ 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: node index.js
